version: "3.4"
services:
  mage:
    image: mage-dev
    build:
      context: ./
      dockerfile: ./.docker/dev/Dockerfile
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    working_dir: /public_html
    volumes:
      - ./src/test.php:/public_html/test.php
      - ./bin/n98:/public_html/bin/n98
      - ./config.php:/public_html/app/etc/config.php
      - ./env.php:/public_html/app/etc/env.php
      - ./src/app/code:/public_html/app/code
      - ./src/app/design/:/public_html/app/design
      - ./src/generated:/public_html/generated
      - ./src/vendor:/public_html/vendor
      - pub_errors:/public_html/pub/errors
      - pub_assets:/public_html/pub/assets
      - pub_well-known:/public_html/pub/.well-known
      - pub_opt:/public_html/pub/opt
      - media:/public_html/pub/media
      - static:/public_html/pub/static
      - setup:/public_html/setup
      - var:/public_html/var
      - ./settings/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=Mage2.local"
    depends_on:
      - database
  database:
    image: mysql:8
    environment:
      - COMPOSE_INTERACTIVE_NO_CLI=1
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci  --default-authentication-plugin=mysql_native_password
    volumes:
      - ./settings/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:rw
      - ./settings/mysql/01_entry_init_db.sh:/docker-entrypoint-initdb.d/01_entry_init_db.sh
      - ./db:/docker-entrypoint-initdb-multi.d
    cap_add:
      - SYS_NICE
    tty: true
    stdin_open: true
    ports:
      - 3306:3306
  nginx:
    image: "nginx:latest"
    working_dir: /public_html
    volumes:
      - pub_errors:/public_html/pub/errors
      - pub_assets:/public_html/pub/assets
      - pub_well-known:/public_html/pub/.well-known
      - pub_opt:/public_html/pub/opt
      - ./src/pub/index.php:/public_html/pub/index.php
      - ./src/pub/cron.php:/public_html/pub/cron.php
      - ./src/pub/get.php:/public_html/pub/get.php
      - ./src/pub/static.php:/public_html/pub/static.php
      - ./src/pub/health_check.php:/public_html/pub/health_check.php
      - ./src/pub/.user.ini:/public_html/pub/.user.ini
      - static:/public_html/pub/static
      - media:/public_html/pub/media
      - setup:/public_html/setup
      - ./settings/site/default.conf.template:/etc/nginx/conf.d/default.conf.template:rw
      - ./settings/site/mage2.conf:/etc/nginx/setting/mage2.conf
      - ./logs/nginx:/var/log/nginx
    command: /bin/bash -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    environment:
      - MAGE_MODE=developer
      - DOMAIN=staging.damda.com
    ports:
      - "80:80"
    depends_on:
      - mage
    links:
      - "mage:fpm"
  redis:
    image: redis
    working_dir: /data
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
  elasticsearch:
    image: "elastic/elasticsearch:7.17.7"
    environment:
      ES_JAVA_OPTS: "${ES_JAVA_OPTS:--Xms512m -Xmx512m}"
      discovery.type: "single-node"
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
    ports:
      - 8080:80
    depends_on:
      - database
volumes:
  pub_errors:
  pub_assets:
  pub_well-known:
  pub_opt:
  setup:
  static:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./static
  media:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./media
  var:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./var
