#!/bin/sh
set -ex
if [ ! -d "/public_html/vendor" ]; then
    composer install
fi

echo "Install Magento"
INSTALL_COMMAND="bin/magento setup:install \
        --base-url=http://${DOMAIN:-localhost} \
        --base-url-secure=https://${DOMAIN:-localhost} \
        --db-host=${VARIABLE:-database} \
        --db-name=${DATABASE:-mage} \
        --db-user=${DATABASE_USER:-root} \
        --db-password=${DATABASE_PASSWORD:-root} \
        --admin-firstname=admin \
        --admin-lastname=admin \
        --admin-email=admin@admin.com \
        --admin-user=admin \
        --admin-password=admin123 \
        --backend-frontname=${BACKEND_FRONTNAME:-admin} \
        --language=en_US \
        --currency=USD \
        --timezone=America/Chicago \
        --use-rewrites=1 --cleanup-database \
        --search-engine=${ELS_VERSION:-elasticsearch7} \
        --elasticsearch-host=${ELS_HOST:-els} \
        --elasticsearch-port=${ELS_PORT:-9200}"

$INSTALL_COMMAND
bin/magento setup:upgrade
bin/magento setup:static-content:deploy -f
